### ISSUE TITLE
[Crash] AttributeError("'int' object has no attribute 'startswith'")

### ISSUE THREAD

**Issue by WarnerMeinshegran** [definite-d/PSG-LookyFeely#14]
### Error message:
```shell
Traceback (most recent call last):
  File "themera.py", line 1029, in main
  File "themera.py", line 472, in __call__
  File "themera.py", line 762, in read
  File "palette_preview.py", line 50, in palette_preview
  File "palette_preview.py", line 50, in <lambda>
  File "colour.py", line 988, in __init__
  File "colour.py", line 1006, in __setattr__
  File "colour.py", line 1084, in set_web
  File "colour.py", line 664, in web2hex
AttributeError: 'int' object has no attribute 'startswith'
```
### User Report/Messages:
Full preview palate
### Time of Crash:
2023-09-22 16:04:04.806934
### Platform info:
Linux-5.15.0-84-generic-x86_64-with-glibc2.35
### Processor:
x86_64
#### Themera Version:
2.1.0
#### PySimpleGUI Version:
4.60.5
#### Reskinner Version:
2.3.8
#### Python Version:
3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

**Comment by definite-d** [comment]
I've replicated the issue, and will get to fixing it now. Thanks for reporting.

**Comment by definite-d** [comment]
I've replicated the issue, and will get to fixing it now. Thanks for reporting.

**Comment by definite-d** [comment]
Okay, fixed. I'll compile and upload the patch release.

**Comment by definite-d** [comment]
Okay, fixed. I'll compile and upload the patch release.
